version: '3.8'

services:
  telegram-scheduler:
    container_name: telegram-scheduler
    build: .
    ports:
      - "8088:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=your_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
    restart: always
